<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="isLeapYear" Id="{2336ce5d-2854-4e52-acb8-01e004829e85}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION isLeapYear : Bool
VAR_INPUT
	nYear	: INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[isLeapYear := (nYear / 4 = 0) AND (nYear / 100 <> 0) OR (nYear /400 = 0);]]></ST>
    </Implementation>
    <LineIds Name="isLeapYear">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>